# Generated by Django 4.2.6 on 2023-10-05 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cat', models.IntegerField()),
                ('nombre_cat', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('fecha_eva', models.DateField(null=True)),
                ('fecha_pmyac', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_resp', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rec', models.IntegerField()),
                ('recomendacion', models.TextField()),
                ('meta', models.TextField()),
                ('plazo_cumplimiento', models.DateTimeField(auto_now_add=True, null=True)),
                ('indicador_validacion', models.CharField(max_length=255)),
                ('acciones_meta', models.TextField()),
                ('recursos', models.TextField()),
                ('archivo', models.FileField(upload_to='archivos_pdf/')),
                ('observacion', models.TextField(null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.responsable')),
            ],
        ),
        migrations.CreateModel(
            name='Eje_eval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_eje', models.IntegerField()),
                ('nombre_eje', models.CharField(max_length=90)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evaluacion')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='eje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eje_eval'),
        ),
    ]
