# Generated by Django 4.2.6 on 2024-10-14 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_recomendacion_plazo_cumplimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacion',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='recomendacion',
            name='responsable',
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='responsables',
            field=models.ManyToManyField(to='api.responsable'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='plazo_cumplimiento',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(null=True, upload_to='')),
                ('recomendacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='api.recomendacion')),
            ],
        ),
    ]
